diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=C:/Users/Calidad Profesional/Desktop/Desk/Programas/Git/mingw64/etc/ssl/certs/ca-bundle.crt
core.autocrlf=input
core.fscache=true
core.symlinks=false
pull.rebase=false
credential.helper=manager
credential.https://dev.azure.com.usehttppath=true
init.defaultbranch=master
user.email=nati.mius@gmail.com
user.name=Natitatalia
user.ui=true
core.editor=code --wait
core.autocrlf=true
core.autrcrlf=TRUE
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
remote.origin.url=https://github.com/Natitatalia/natitatalia.github.io.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.principal.remote=origin
branch.principal.merge=refs/heads/principal
